# Generated by Django 5.0.1 on 2025-08-16 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JuraUser",
            fields=[
                (
                    "auth_hash",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hash must be valid hexadecimal characters",
                                regex="^[a-fA-F0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "recover_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hash must be valid hexadecimal characters",
                                regex="^[a-fA-F0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "encrypted_secret_key",
                    models.BinaryField(blank=True, max_length=1024, null=True),
                ),
                ("recovery_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
